Added exception handling in MathOperations
tg-trainer/TGT_Scala_23-24 pull request #3
Opened 2023-11-07 11:29 UTC by Shubhang-2111

Made changes as per the feedback

2023-11-07 19:40 UTC, tg-trainer commented on src/main/scala/shubhang/TGTraining.scala
> +  def divide(): Any = {
never use any as we talked

2023-11-07 19:40 UTC, tg-trainer requested changes
Do the required changes

2023-11-08 10:55 UTC, Shubhang-2111 reviewed
Made the return type to Int from any.

2023-11-08 14:00 UTC, tg-trainer requested changes

2023-11-08 14:00 UTC, tg-trainer commented on src/main/scala/shubhang/TGTraining.scala
> +class TGTraining(num1:Int,num2:Int) {
This should be param for your functions otherwise you need to make new object for each new value

2023-11-09 16:54 UTC, Shubhang-2111 reviewed
Passed the params in function instead of class as per the feedback

2023-11-09 18:15 UTC, merged