copied assignment to new repo and modified as per previous feed back …
tg-trainer/TGT_Scala_23-24 pull request #4
Opened 2023-11-07 12:57 UTC by M-Madhavreddy

…along with exception handling methods

2023-11-07 19:39 UTC, tg-trainer commented on src/test/scala/m_madhav_reddy/BasicCalculatorTesting.scala
> +
remove empty lines

2023-11-07 19:39 UTC, tg-trainer requested changes
Please check your spacing

2023-11-08 06:49 UTC, M-Madhavreddy commented
changed as per request

2023-11-08 13:05 UTC, M-Madhavreddy reviewed
Removed extra space

2023-11-09 18:53 UTC, merged