Tweaked Assignment-1 with all the advised feedbacks.
tg-trainer/TGT_Scala_23-24 pull request #5
Opened 2023-11-07 14:54 UTC by Kushagra4679

2023-11-07 19:37 UTC, tg-trainer commented on src/main/scala/kushagra/CalculationOperations.scala
> +  def product(num1: Long, num2: Long): Long = {
leave a line after a function & before a class

2023-11-07 19:38 UTC, tg-trainer commented on src/main/scala/kushagra/CalculationOperations.scala
> +    // dividend is taken in Double to ensure the calculation happens
if you wanna add comment for any functionality. Try to put it before function definition

2023-11-07 19:38 UTC, tg-trainer requested changes
Let me know once you are done with changes

2023-11-08 06:37 UTC, Kushagra4679 commented on src/main/scala/kushagra/CalculationOperations.scala
> +  def product(num1: Long, num2: Long): Long = {
Done sir.

2023-11-08 06:40 UTC, Kushagra4679 commented on src/main/scala/kushagra/CalculationOperations.scala
> +  def product(num1: Long, num2: Long): Long = {
Both the feedbacks have addressed :)

2023-11-08 06:42 UTC, Kushagra4679 commented
> Let me know once you are done with changes

Both the changes are now applied in the CodeBase.

2023-11-08 13:59 UTC, merged