Updated Code with Exception Handling
tg-trainer/TGT_Scala_23-24 pull request #6
Opened 2023-11-07 15:38 UTC by Srishti-Chhabra

This is the updated code with all the issues fixed, as said. It also includes three methods for handling exceptions.

2023-11-07 19:35 UTC, tg-trainer commented on src/main/scala/srishti/TGTraining.scala
> +object Main
remove it

2023-11-07 19:35 UTC, tg-trainer commented on src/main/scala/srishti/TGTraining.scala
> +object Main
as we have the unit test

2023-11-07 19:36 UTC, tg-trainer requested changes
please do the requested changes

2023-11-08 08:19 UTC, Srishti-Chhabra commented on src/main/scala/srishti/TGTraining.scala
> +object Main
Done Sir!

2023-11-08 13:30 UTC, Srishti-Chhabra commented
Updated Code with Exception Handling by Srishti-Chhabra · Pull Request #6 ·
tg-trainer/TGT_Scala_23-24 (github.com)
<https://github.com/tg-trainer/TGT_Scala_23-24/pull/6#discussion_r1386176474>

Done the suggested changes, Sir. Please review them.
Thank you!

On Wed, Nov 8, 2023 at 1:06 AM Ayush Tiwari ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> please do the requested changes
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tg-trainer/TGT_Scala_23-24/pull/6#pullrequestreview-1718571856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBLVIP5FANTBSONIA7S4ELDYDKEUJAVCNFSM6AAAAAA7BMWNNGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMJYGU3TCOBVGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-09 18:53 UTC, merged