Adding Basic Calculator
tg-trainer/TGT_Scala_23-24 pull request #8
Opened 2023-11-08 02:42 UTC by abhishekbansal276

I have added basic calculator class. Please accept my PR and give me feedback.

2023-11-08 03:41 UTC, tg-trainer requested changes
Please update the name at all the places

2023-11-08 03:41 UTC, tg-trainer commented on src/main/scala/abhishek_bansal/basic_calculator/BasicCalculator.scala
> +      case "Addition" => Right(value_1 + value_2)
variable name should be in lowerCamelCase case only

2023-11-08 13:03 UTC, tg-trainer requested changes
Let me know when you are done

2023-11-08 13:03 UTC, tg-trainer commented on src/main/scala/abhishek_bansal/basic_calculator/BasicCalculator.scala
> +    if (value2 != 0) Right(value1 / value2)
don't use the number

2023-11-09 08:55 UTC, abhishekbansal276 commented on src/main/scala/abhishek_bansal/basic_calculator/BasicCalculator.scala
> +    if (value2 != 0) Right(value1 / value2)
done sir

2023-11-09 10:25 UTC, merged